### ISSUE TITLE
Detecting when prompt timed out

### ISSUE THREAD

**Issue by jgillich** [synzen/discord.js-prompts#1]
Hey, great library! :+1: 

I just have one tiny complaint. :wink: Given this code:

```js
try {
    const data = await runner.run(foo, channel);
    channel.send(`You did it!`);
} catch (error) {
    log.error(`blabla ${error.message}`);
    channel.send(`That didn't work..`);
}
```

When I run this and don't respond to the prompts, the result looks like this:

> Menu closed due to inactivity.
> You did it!

It's not clear to me how to handle the timeout here. I can check that the values from the last prompt are set, but that's not a great solution IMHO. Thoughts?

**Comment by synzen** [comment]
Hey there, great to hear. As a general rule all responses should be encapsulated within prompts (and subsequently, within nodes). If a timeout occurs at any one of the nodes, execution will stop there, skipping all subsequent nodes. So all you have to do is use another prompt without a function like so:

```js
const successVisual = (data) => {
  return new MessageVisual(`You did it!`)
}
const successPrompt = new DiscordPrompt(successVisual)
```
put it in a node, and so on

The goal of this library was to completely avoid writing `channel.send` within the `message` listener of the discord.js client wherever possible, so you should ideally convert that `message.send` in the try block into another prompt as well. This can result in significantly cleaner and understandable code, like so:

```js
const doActionNode = new PromptNode(doActionPrompt)

const successNodeCondition = (data) => data.myCondition === true
const successNode = new PromptNode(sucessPrompt, successNodeCondition)

const failNodeCondition = (data) => data.myCondition === false
const failNode = new PromptNode(failPrompt, failNodeCondition)

doActionNode.setChildren([
  successNode,
  failNode
])
// run with the root doActionNode
```

Additionally, putting all responses as prompts will let the lib centralize the errors that could normally occur from `channel.send` by throwing it during the `.run` execution

Docs are a bit sparse right now, so apologies about that

**Comment by jgillich** [comment]
My issue isn't so much about the message reply but more about how do I know the prompt was actually completed and I can use the data. Your example relies on checking data properties just like I'm doing currently, which can easily break when the data changes (caused by a programming error, but still). Let's take the example: https://github.com/synzen/discord.js-prompts/blob/master/src/examples/askPersonDetails.js#L54

When I run this code and let it time out, data is set to:
```
{ __authorID: '132433429412315136' }
```
To use the data, I'd now have to do something like:
```
if(data.age && data.name) {
  // ...
}
```

This is not a great solution in my opinion. As far as my use-case is concerned, a timeout is an error, and so it would be good to know about it.

**Comment by synzen** [comment]
I see - I believe you want to do the work after the PromptRunner's `run`. The hope was that all work can be done within prompts, and not after them (contrary to what the example implies, I admit). So for the example

```js
const askAgeFn = async (m, data) => {
  const age = Number(m.content)
  if (isNaN(age)) {
    throw new Rejection(`That's not a valid number. Try again.`)
  }
  // do work here, both data.name and age are guaranteed to be defined (given the node order)
  return {
    ...data,
    age
  }
}
```
This way:
1. By the time askAgeFn runs, all previous nodes were completed successfully along with all property additions
2. Whatever you added to the `data` object in the previous prompt nodes are guaranteed to exist with no need for explicit checks
3. The work that requires them can be done

I see what you're saying about timeouts though. There are two ways prompts can be prematurely finished:
1. On inactivity 
2. If the user manually types `exit`

I did not consider them to be errors, since they aren't in the traditional sense (permissions, programming, and etc.). But I suppose it ultimately doesn't make much sense that `run` resolves when it prematurely ends, when the reasonable expectation is that it finished.

I'll make them throw custom errors in the next release (something like `InactivityError` and `VoluntaryExitError`, both instances of a parent like `UserExitError`). Since this will be a breaking change, it will be a major version update.

**Comment by jgillich** [comment]
Sounds good, thank you!

**Comment by synzen** [comment]
2.0.0 now has the breaking changes implemented - see https://github.com/synzen/discord.js-prompts/releases/tag/2.0.0. Thanks for the feedback.
