### ISSUE TITLE
Prompt duration doesn't seem to apply

### ISSUE THREAD

**Issue by JamesHawkinss** [synzen/discord.js-prompts#5]
When using `new Prompt(visual, fn, 600000)` where 600000 is the duration (10 minutes), the prompt doesn't wait for 10 minutes before continuing. Am I using this incorrectly?

Thanks in advance!

**Comment by synzen** [comment]
It seems you are - the duration is the maximum length of time the prompt will wait for input until it *expires*, not until it continues. For more information, see 

https://github.com/synzen/prompt-anything#time-limitstimeouts

It is only used to automatically end the prompt if the user doesn't respond in a timely manner, otherwise it would run forever.

**Comment by JamesHawkinss** [comment]
Ah sorry, I obviously wasn't thinking when I wrote this.

It doesn't wait the 10 minutes - if a user fails to enter anything within 2 minutes it times out.

**Comment by synzen** [comment]
I see the issue - thanks for the report. At the moment, it's constantly using the default 90 second timeout instead of the value you pass in. I'll try and get a patch out as soon as I can that'll fix this.

**Comment by synzen** [comment]
Fixed in 2.2.1
