### ISSUE TITLE
@User not pinging when msg sent from MessageVisual or Rejection

### ISSUE THREAD

**Issue by Dinip** [synzen/discord.js-prompts#7]
I was trying to mention the user when the prompt asks the questions. I was trying to achieve this with `<@${data.__authorID}>`, which works when sending the message normally with `message.channel.send('<@${authorId}>')`. There are 2 prints below, one is a snippet of the code and the other is a message with a mention sent "normally" and then sent via the code below!

![image](https://user-images.githubusercontent.com/8941012/98450003-ad070f80-2130-11eb-969a-3745afe24b22.png)
![image](https://user-images.githubusercontent.com/8941012/98449923-eb4fff00-212f-11eb-8b50-6628e5b56695.png)

Any solution possible for this? Or am I just a noob? 🤔 
Thanks

**Comment by synzen** [comment]
Thanks for making an issue. I see that you are being mentioned, but not actually pinged. This is because the default options for sending a message is:

https://github.com/synzen/discord.js-prompts/blob/61087863ab534e9013b1c63544b7f4cf3b247541/src/DiscordChannel.ts#L17-L21

Which disables both role and user pings. To override this, pass the object
```js
const options = {
   allowedMentions: { 
     parse: ["users"] 
   } 
 } 
```
to the second argument of `MessageVisual`, like so: `new MessageVisual('text', options)`. The same can be done for roles if you add `"roles"` to the array. ([Discord API reference](https://discord.com/developers/docs/resources/channel#allowed-mentions-object)).

I see though that this can be confusing because this is not typical/default behavior. I'll consider removing this default options object.

**Comment by Dinip** [comment]
Alright! I'm also changing the title of the issue to be more specific about the "pinging" and not really the mention. That's 2 different things now that I think about it! :)

Got the MessageVisual working with the new format mentioned above `new MessageVisual('text', options)` but seems that is not the case with Rejection, that I would also like to ping the user. I read that there is a DiscordRejection but seems that it for embed messages `(text: string, embed?: MessageEmbed)`. Any solution for this too?

Thanks

**Comment by synzen** [comment]
I see. I just released [`3.0.0`](https://github.com/synzen/discord.js-prompts/releases/tag/3.0.0) which will replace the embed param with a `MessageOptions` param, and also removed the default options object.

You can remove the manual override I mentioned since it should ping by default now, according to discord.js's default behavior. The DiscordRejection should also ping users now as well (note the function signature has changed - see the changelog I linked for more details)

Also FYI the `data.__authorID` will eventually be closed off for public access. I never intended it for public access since it is critical for the prompts to work correctly, but it was a bad idea mixing it in with user-provided data. I suggest you pass it in the original data object in `PromptRunner` as `{authorId: message.author.id}` going forward.

**Comment by Dinip** [comment]
> Also FYI the `data.__authorID` will eventually be closed off for public access. I never intended it for public access since it is critical for the prompts to work correctly, but it was a bad idea mixing it in with user-provided data. I suggest you pass it in the original data object in `PromptRunner` as `{authorId: message.author.id}` going forward.

I was doing that at the beginning but then I saw that there was already a `__authorId` present in `data`.

Thanks! I will try it!

**Comment by synzen** [comment]
I'm guessing that this is solved?
